"use client"

import * as React from "react"
import Link from "next/link"
import { useParams } from "next/navigation"
import {
  ArrowLeft,
  UserCheck,
  UserRound,
  UsersRound,
  MapPin,
  Phone,
  Mail,
  Store,
  ShoppingCart,
  FileText,
  Clock,
  X,
  Building2,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FinancialSummary } from "@/components/admin/financial-summary"
import {
  initialOfficers,
  initialOfficerCustomers,
  initialOrders,
  getOfficerFinancialData,
  type SalesOfficerItem,
  type Order,
} from "@/lib/mock-data"

export default function SalesOfficerDetailPage() {
  const params = useParams()
  const officerId = (params?.id as string) || "off-1"

  const [selectedInvoice, setSelectedInvoice] = React.useState<Order | null>(null)

  // Find Officer
  const officer: SalesOfficerItem = React.useMemo(() => {
    return (
      initialOfficers.find(
        (o) => o.id === officerId || o.code.toLowerCase() === officerId.toLowerCase()
      ) || initialOfficers[0]
    )
  }, [officerId])

  // Officer Financial Performance Data
  const financialData = React.useMemo(() => {
    return getOfficerFinancialData(officer.id, officer.totalSales)
  }, [officer.id, officer.totalSales])

  // Customers assigned to this officer
  const assignedCustomers = React.useMemo(() => {
    const matched = initialOfficerCustomers.filter((c) => c.officerId === officer.id)
    return matched.length > 0 ? matched : initialOfficerCustomers.slice(0, 3)
  }, [officer.id])

  // Orders / Invoices generated by this officer
  const officerOrders: Order[] = React.useMemo(() => {
    return initialOrders.filter((o) => o.officerId === officer.id)
  }, [officer.id])

  return (
    <div className="space-y-4">
      {/* Back Navigation Bar */}
      <div>
        <Link
          href="/officers"
          className="inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="size-3.5" />
          <span>Back to Sales Officers</span>
        </Link>
      </div>

      {/* Officer Profile Overview Card */}
      <Card className="border-border/80 bg-card shadow-xs">
        <CardContent className="p-4 sm:p-4.5">
          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            {/* Officer Details */}
            <div className="flex items-center gap-3">
              <div className="flex size-10 items-center justify-center rounded-md border border-primary/20 bg-primary/10 text-primary sm:size-11">
                <UserCheck className="size-5" />
              </div>
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <h1 className="text-lg font-bold tracking-tight text-foreground sm:text-xl">
                    {officer.name}
                  </h1>
                  <span className="rounded-sm border border-primary/20 bg-primary/5 px-2 py-0.5 font-mono text-xs font-semibold text-primary">
                    {officer.code}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1">
                    <MapPin className="size-3 text-muted-foreground" />
                    <span>Assigned Area: <strong className="text-foreground">{officer.areaName}</strong></span>
                  </span>
                  <span className="flex items-center gap-1">
                    <UserRound className="size-3 text-muted-foreground" />
                    <span>RM: <strong className="text-foreground">{officer.rmName}</strong></span>
                  </span>
                  <span className="flex items-center gap-1">
                    <UsersRound className="size-3 text-muted-foreground" />
                    <span>AM: <strong className="text-foreground">{officer.amName}</strong></span>
                  </span>
                  <span className="flex items-center gap-1 font-mono">
                    <Phone className="size-3 text-muted-foreground" />
                    <span>{officer.phone}</span>
                  </span>
                  <span className="flex items-center gap-1">
                    <Mail className="size-3 text-muted-foreground" />
                    <span>{officer.email}</span>
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="mt-3.5 grid grid-cols-1 gap-2.5 border-t border-border/60 pt-3 sm:grid-cols-2">
            <div className="rounded border border-border/60 bg-muted/30 px-3 py-2">
              <span className="text-[11px] font-medium text-muted-foreground">
                Assigned Customers
              </span>
              <p className="mt-0.5 text-base font-bold text-foreground">
                {assignedCustomers.length} <span className="text-xs font-normal text-muted-foreground">Shops</span>
              </p>
            </div>
            <div className="rounded border border-border/60 bg-muted/30 px-3 py-2">
              <span className="text-[11px] font-medium text-muted-foreground">
                Orders Generated
              </span>
              <p className="mt-0.5 text-base font-bold text-primary">
                {officerOrders.length} <span className="text-xs font-normal text-muted-foreground">Invoices</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Financial Performance Summary (6-Card Section) */}
      <FinancialSummary
        data={financialData}
        title={`Financial Performance Summary (${officer.name})`}
      />

      {/* Section 1: Assigned Customers */}
      <Card className="border-border/80 bg-card shadow-xs">
        <CardHeader className="border-b border-border/70 px-4 py-2.5">
          <div className="flex items-center gap-2">
            <Store className="size-4 text-primary" />
            <CardTitle className="text-xs font-semibold text-foreground sm:text-sm">
              Assigned Customers under {officer.name} ({assignedCustomers.length})
            </CardTitle>
          </div>
        </CardHeader>

        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-border bg-muted/40 text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">
                <tr>
                  <th scope="col" className="w-14 px-3.5 py-2.5 text-center">
                    SL
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Customer Code
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Customer Name
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Shop / Pharmacy Name
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Phone
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Area
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60">
                {assignedCustomers.length > 0 ? (
                  assignedCustomers.map((cust, index) => (
                    <tr
                      key={cust.id}
                      className="transition-colors hover:bg-muted/30"
                    >
                      <td className="px-3.5 py-2.5 text-center font-medium text-muted-foreground">
                        {index + 1}
                      </td>
                      <td className="px-3.5 py-2.5 font-mono font-semibold text-primary">
                        {cust.code}
                      </td>
                      <td className="px-3.5 py-2.5 font-semibold text-foreground">
                        <Link
                          href={`/customers/${cust.id}`}
                          className="transition-colors hover:text-primary hover:underline"
                        >
                          {cust.name}
                        </Link>
                      </td>
                      <td className="px-3.5 py-2.5 text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Store className="size-3 text-muted-foreground" />
                          <span className="font-medium text-foreground">{cust.shopName}</span>
                        </span>
                      </td>
                      <td className="px-3.5 py-2.5 font-mono text-[11px] text-muted-foreground">
                        {cust.phone}
                      </td>
                      <td className="px-3.5 py-2.5 text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <MapPin className="size-3 text-muted-foreground" />
                          {cust.areaName}
                        </span>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td
                      colSpan={6}
                      className="px-4 py-6 text-center text-xs text-muted-foreground"
                    >
                      No customers assigned to this Sales Officer yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Section 2: Invoices / Orders Generated by Officer */}
      <Card className="border-border/80 bg-card shadow-xs">
        <CardHeader className="border-b border-border/70 px-4 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <ShoppingCart className="size-4 text-primary" />
              <CardTitle className="text-xs font-semibold text-foreground sm:text-sm">
                Invoices / Orders Generated by {officer.name} ({officerOrders.length})
              </CardTitle>
            </div>
            <span className="text-[11px] text-muted-foreground">
              Total Order Value: <strong className="font-mono text-primary font-bold">৳ {officerOrders.reduce((sum, o) => sum + o.grandTotal, 0).toLocaleString()}</strong>
            </span>
          </div>
        </CardHeader>

        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-border bg-muted/40 text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">
                <tr>
                  <th scope="col" className="w-12 px-3.5 py-2.5 text-center">
                    SL
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Invoice ID
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Customer / Shop
                  </th>
                  <th scope="col" className="px-3.5 py-2.5">
                    Date & Time
                  </th>
                  <th scope="col" className="px-3.5 py-2.5 text-center">
                    Total Items
                  </th>
                  <th scope="col" className="px-3.5 py-2.5 text-right">
                    Grand Total
                  </th>
                  <th scope="col" className="px-3.5 py-2.5 text-center">
                    Order Status
                  </th>
                  <th scope="col" className="w-28 px-3.5 py-2.5 text-right">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60">
                {officerOrders.length > 0 ? (
                  officerOrders.map((ord, index) => (
                    <tr
                      key={ord.id}
                      className="transition-colors hover:bg-muted/30"
                    >
                      <td className="px-3.5 py-2.5 text-center font-medium text-muted-foreground">
                        {index + 1}
                      </td>
                      <td className="px-3.5 py-2.5 font-mono font-semibold text-primary">
                        {ord.code}
                      </td>
                      <td className="px-3.5 py-2.5">
                        <Link
                          href={`/customers/${ord.customerId}`}
                          className="font-semibold text-foreground hover:text-primary hover:underline block"
                        >
                          {ord.shopName}
                        </Link>
                        <span className="text-[10px] text-muted-foreground">{ord.customerName}</span>
                      </td>
                      <td className="px-3.5 py-2.5 text-muted-foreground">
                        <div className="flex items-center gap-1.5 text-[11px]">
                          <Clock className="size-3 text-muted-foreground" />
                          <span>{ord.date}</span>
                        </div>
                      </td>
                      <td className="px-3.5 py-2.5 text-center font-medium text-foreground">
                        {ord.totalItems} units
                      </td>
                      <td className="px-3.5 py-2.5 text-right font-mono font-bold text-foreground">
                        ৳ {ord.grandTotal.toLocaleString()}
                      </td>
                      <td className="px-3.5 py-2.5 text-center">
                        <span
                          className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold ${
                            ord.status === "Approved"
                              ? "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                              : ord.status === "Pending"
                              ? "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400"
                              : "border-destructive/20 bg-destructive/10 text-destructive"
                          }`}
                        >
                          {ord.status}
                        </span>
                      </td>
                      <td className="px-3.5 py-2.5 text-right">
                        <Button
                          type="button"
                          variant="outline"
                          size="xs"
                          onClick={() => setSelectedInvoice(ord)}
                          className="cursor-pointer gap-1 text-[11px] font-medium hover:bg-primary hover:text-primary-foreground"
                        >
                          <FileText className="size-3" />
                          <span>View Invoice</span>
                        </Button>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={8} className="px-4 py-6 text-center text-xs text-muted-foreground">
                      No invoices generated by this Sales Officer yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      {/* Invoice Details Modal */}
      {selectedInvoice && (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
        >
          <div
            onClick={() => setSelectedInvoice(null)}
            className="fixed inset-0 bg-black/60 backdrop-blur-xs transition-opacity"
          />

          <div className="relative z-10 w-full max-w-lg rounded-md border border-border bg-card p-5 shadow-2xl max-h-[85vh] flex flex-col">
            <div className="flex items-center justify-between border-b border-border/60 pb-3">
              <div className="flex items-center gap-2">
                <FileText className="size-4 text-primary" />
                <h3 className="text-base font-semibold text-foreground">
                  Invoice Details &mdash; {selectedInvoice.code}
                </h3>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon-xs"
                onClick={() => setSelectedInvoice(null)}
                className="text-muted-foreground hover:text-foreground cursor-pointer"
              >
                <X className="size-4" />
              </Button>
            </div>

            <div className="mt-3 space-y-3 text-xs overflow-y-auto flex-1 pr-1">
              <div className="grid grid-cols-2 gap-2 rounded border border-border/70 bg-muted/20 p-2.5">
                <div>
                  <span className="text-[10px] text-muted-foreground block uppercase font-semibold">Customer / Shop</span>
                  <span className="font-semibold text-foreground">{selectedInvoice.shopName}</span>
                </div>
                <div>
                  <span className="text-[10px] text-muted-foreground block uppercase font-semibold">Proprietor</span>
                  <span className="font-medium text-foreground">{selectedInvoice.customerName}</span>
                </div>
                <div>
                  <span className="text-[10px] text-muted-foreground block uppercase font-semibold">Date & Time</span>
                  <span className="text-muted-foreground font-mono">{selectedInvoice.date}</span>
                </div>
                <div>
                  <span className="text-[10px] text-muted-foreground block uppercase font-semibold">Order Status</span>
                  <span
                    className={`inline-flex items-center rounded px-1.5 py-0.5 text-[10px] font-semibold ${
                      selectedInvoice.status === "Approved"
                        ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                        : selectedInvoice.status === "Pending"
                        ? "bg-amber-500/10 text-amber-600 dark:text-amber-400"
                        : "bg-destructive/10 text-destructive"
                    }`}
                  >
                    {selectedInvoice.status}
                  </span>
                </div>
              </div>

              {/* Items Table */}
              <div className="space-y-1.5">
                <span className="text-[11px] font-semibold text-foreground">
                  Order Items Breakdown ({selectedInvoice.items?.length} Products)
                </span>
                <div className="rounded border border-border/60 overflow-hidden">
                  <table className="w-full text-left text-xs">
                    <thead className="border-b border-border bg-muted/40 text-[10px] font-semibold uppercase text-muted-foreground">
                      <tr>
                        <th className="px-2.5 py-1.5">Product</th>
                        <th className="px-2.5 py-1.5">Pack</th>
                        <th className="px-2.5 py-1.5 text-center">Qty</th>
                        <th className="px-2.5 py-1.5 text-right">Price</th>
                        <th className="px-2.5 py-1.5 text-right">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border/60">
                      {selectedInvoice.items?.map((item, idx) => (
                        <tr key={idx} className="hover:bg-muted/20">
                          <td className="px-2.5 py-2 font-medium text-foreground">{item.productName}</td>
                          <td className="px-2.5 py-2 text-muted-foreground font-mono text-[11px]">{item.packSize}</td>
                          <td className="px-2.5 py-2 text-center font-mono font-semibold">{item.quantity}</td>
                          <td className="px-2.5 py-2 text-right font-mono text-muted-foreground">৳{item.unitPrice}</td>
                          <td className="px-2.5 py-2 text-right font-mono font-semibold text-foreground">
                            ৳{item.totalPrice.toLocaleString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Financial Totals */}
              <div className="rounded border border-border/60 bg-muted/10 p-3 space-y-1.5 text-xs">
                <div className="flex justify-between text-muted-foreground">
                  <span>Subtotal:</span>
                  <span className="font-mono">৳ {selectedInvoice.subtotal.toLocaleString()}</span>
                </div>
                {selectedInvoice.discountAmount > 0 && (
                  <div className="flex justify-between text-amber-600 dark:text-amber-400">
                    <span>Discount ({selectedInvoice.discountPercent}%):</span>
                    <span className="font-mono">- ৳ {selectedInvoice.discountAmount.toLocaleString()}</span>
                  </div>
                )}
                <div className="flex justify-between font-bold text-foreground border-t border-border/60 pt-1.5">
                  <span>Grand Total:</span>
                  <span className="font-mono text-primary text-sm">৳ {selectedInvoice.grandTotal.toLocaleString()}</span>
                </div>
              </div>
            </div>

            <div className="mt-4 flex items-center justify-end border-t border-border/60 pt-3">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setSelectedInvoice(null)}
                className="cursor-pointer text-xs"
              >
                Close
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
